name: Live-debugger landing page build check
on:
    pull_request:
        paths:
            - ".github/workflows/landing-build-check.yml"
            - landing/**
    merge_group:
        branches:
            - main
    workflow_call:
    workflow_dispatch:

jobs:
    live-debugger-landing-build-check:
        if: github.repository == 'software-mansion/live-debugger'
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v4
              with:
                  submodules: "true"
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "npm"
                  cache-dependency-path: landing/package-lock.json
            - name: Install node dependencies
              working-directory: landing
              run: npm install
            - name: Build landing page
              working-directory: landing
              run: npm run build
